{{define "Dockerfile_env"}}

# Required Test-Flight Working dir
ENV WORKDIR {{.WorkDir}}/{{.ImageName}}

{{if .Env}}
# -----> Env entries
{{range $key, $entry := .Env}}
ENV {{$entry.Variable}} {{$entry.Value}}
{{end}}
# <----- end Env
{{end}}

{{end}}
