{{define "Dockerfile_header"}}
#
# ------------------------------------------------------
#                       Dockerfile
# ------------------------------------------------------
# image:    {{.ImageName}}
# tag:      {{.Tag}}
# name:     {{.Owner}}/{{.ImageName}}
# version:  v{{.Version}}
# how-to:   docker build -t {{.Owner}}/{{.ImageName}} .
# Requires: {{.From}}
#
#       Test-Flight v{{.Meta.Version}} Generated Dockerfile
# ------------------------------------------------------

FROM {{.From}}
MAINTAINER {{.Owner}}
{{end}}