{{define "Dockerfile_add"}}
{{if .AddSimple}}
# -----> Add Simple Entries
{{range $item := .AddSimple}}
ADD {{$item}} $WORKDIR/{{$item}}
{{end}}
# <----- end Add System Entries
{{end}}

{{if .AddComplex}}
# -----> Add Complex Entries
{{range $item := .AddComplex}}
ADD {{$item.Name}} {{$item.Location}}
{{end}}
# <----- end Add Complex Entries
{{end}}

# Required Test-Flight test-flight playbook and inventory
ADD .test-flight/inventory /etc/ansible/hosts
ADD .test-flight/playbook.yml $WORKDIR/playbook.yml
{{end}}
